spring:
  datasource:
    #url: jdbc:h2:tcp://localhost/~/mybit
    #username: sa
    #password:
    #driver-class-name: org.h2.Driver
    url: jdbc:mysql://localhost:3306/mybit
    username: root
    password: "1234"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

logging.level:
  org.hibernate.SQL: debug
